const fs = require('fs')
const path = require('path')

const SRC = path.resolve(__dirname, '..', '..', 'LinkOn.Modeler', 'Common', 'c_QCommon.cs')
const OUT = path.resolve(__dirname, '..', 'src', 'generated', 'iconMap.ts')

// Map relevant Q* classes to raw XML tags used in our tree
const classToTag = {
  QMessage: 'MG',
  QItem: 'IT',
  QConnector: 'CN',
  QSession: 'SN',
}

function main() {
  const text = fs.readFileSync(SRC, 'utf8')
  const map = {}
  const msgRe = /Message_(Eq|Host|Both)_(lock|unlock)/g
  const itemRe = /Item(List)?_(lock|unlock)/g
  const connectorRe = /Connector_(\w+)_?(lock|unlock)?/g

  // Messages
  map['MG'] = {
    default: 'Message_Both_unlock',
    variants: {
      Eq_lock: 'Message_Eq_lock',
      Eq_unlock: 'Message_Eq_unlock',
      Host_lock: 'Message_Host_lock',
      Host_unlock: 'Message_Host_unlock',
      Both_lock: 'Message_Both_lock',
      Both_unlock: 'Message_Both_unlock',
    },
  }

  // Items
  map['IT'] = {
    default: 'Item_unlock',
    variants: {
      List_lock: 'ItemList_lock',
      List_unlock: 'ItemList_unlock',
      Lock: 'ItemLock',
      Unlock: 'Item_unlock',
    },
  }

  // Connector
  map['CN'] = {
    default: 'Connector_Closed_unlock',
  }

  // Session (fallback)
  map['SN'] = {
    default: 'Session',
  }

  const out = `// Auto-generated by scripts/extract-icons.cjs\nexport const IconMap = ${JSON.stringify(map, null, 2)} as const;\nexport type IconMap = typeof IconMap;\n`
  fs.writeFileSync(OUT, out, 'utf8')
  console.log('icon map written to', OUT)
}

if (require.main === module) main()
