const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const PROP_DIR = path.resolve(ROOT, '..', 'LinkOn.Modeler', 'Forms', 'Modeling', 'Message', 'Prop')
const OUT = path.resolve(ROOT, 'src', 'generated', 'propMeta.ts')
const ENUMS = require(path.resolve(ROOT, 'src', 'generated', 'enums.ts')).Enums

const tagMap = {
  'c_QPropMsg.cs': 'MSG',
  'c_QPropItm.cs': 'IT',
  'c_QPropSsn.cs': 'SN',
  'c_QPropMsl.cs': 'ML',
  'c_QPropCnt.cs': 'CN',
  'c_QPropDrv.cs': 'DRV',
}

function parseFile(file) {
  const text = fs.readFileSync(file, 'utf8')
  const categories = {}
  const catRe = /const string (Category\w+)\s*=\s*"([^"]+)"/g
  let m
  while ((m = catRe.exec(text)) !== null) {
    categories[m[1]] = m[2]
  }

  const attrMeta = {}
  let order = 0
  const re = /Properties\["([^"]+)"\]\.attributes\.Replace\(new\s+(DisplayNameAttribute|CategoryAttribute)\(([^)]+)\)\)/g
  let match
  while ((match = re.exec(text)) !== null) {
    const prop = match[1]
    const type = match[2]
    const val = match[3].trim()
    attrMeta[prop] = attrMeta[prop] || {}
    if (!attrMeta[prop].order) {
      order += 1
      attrMeta[prop].order = order
    }
    if (type === 'DisplayNameAttribute') {
      const label = val.replace(/^"/, '').replace(/"$/, '')
      attrMeta[prop].label = label
    } else if (type === 'CategoryAttribute') {
      const catName = categories[val] || val.replace(/"/g, '')
      attrMeta[prop].category = catName
    }
  }

  // Detect property types (for enum binding)
  const propRe = /public\s+([A-Za-z_][A-Za-z0-9_<>,\s]*)\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{/g
  while ((match = propRe.exec(text)) !== null) {
    const typ = match[1].trim().split(/\s+/).pop() // take last token
    const prop = match[2]
    if (!attrMeta[prop]) continue
    if (ENUMS[typ]) {
      attrMeta[prop].enumType = typ
      attrMeta[prop].enumValues = ENUMS[typ]
    }
    // handle nullable / generic like Nullable<QFormat>
    const coreTyp = typ.replace(/Nullable<(.+)>/, '$1').replace(/<.*>/, '')
    if (!attrMeta[prop].enumValues && ENUMS[coreTyp]) {
      attrMeta[prop].enumType = coreTyp
      attrMeta[prop].enumValues = ENUMS[coreTyp]
    }
  }

  return attrMeta
}

function main() {
  const meta = {}
  fs.readdirSync(PROP_DIR).forEach((file) => {
    if (!file.endsWith('.cs')) return
    const tag = tagMap[file]
    if (!tag) return
    meta[tag] = parseFile(path.join(PROP_DIR, file))
  })

  const out = `// Auto-generated by scripts/extract-props.cjs\nexport const PropMeta = ${JSON.stringify(meta, null, 2)} as const;\nexport type PropMeta = typeof PropMeta;\n`
  fs.mkdirSync(path.dirname(OUT), { recursive: true })
  fs.writeFileSync(OUT, out, 'utf8')
  console.log('prop meta written to', OUT)
}

if (require.main === module) main()
