const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const SOURCES = [
  path.resolve(ROOT, '..', 'LinkOn.Modeler'),
  path.resolve(ROOT, '..', 'Core.Common'),
  path.resolve(ROOT, '..', 'Core.Driver'),
  path.resolve(ROOT, '..', 'Core.Common.ValueFilters'),
]
const OUT = path.resolve(ROOT, 'src', 'generated', 'enums.ts')

function findCsFiles(dir) {
  let files = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === 'bin' || entry.name === 'obj' || entry.name.startsWith('.')) continue
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) files = files.concat(findCsFiles(full))
    else if (entry.isFile() && entry.name.endsWith('.cs')) files.push(full)
  }
  return files
}

function parseEnums(text) {
  const enums = []
  const re = /public\s+enum\s+(\w+)[^{]*{([^}]*)}/gms
  let m
  while ((m = re.exec(text)) !== null) {
    const name = m[1]
    const body = m[2]
    const cleaned = body.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '')
    const vals = cleaned
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
      .map((s) => s.replace(/\s*=.*$/, ''))
    enums.push({ name, values: vals })
  }
  return enums
}

function main() {
  const files = SOURCES.flatMap((dir) => (fs.existsSync(dir) ? findCsFiles(dir) : []))
  const enumMap = {}
  for (const file of files) {
    const text = fs.readFileSync(file, 'utf8')
    parseEnums(text).forEach((e) => {
      if (!enumMap[e.name]) enumMap[e.name] = e.values
    })
  }

  const ts = `// Auto-generated by scripts/extract-enums.cjs
export const Enums = ${JSON.stringify(enumMap, null, 2)} as const;
export type Enums = typeof Enums;
`
  fs.mkdirSync(path.join(ROOT, 'src', 'generated'), { recursive: true })
  fs.writeFileSync(OUT, ts, 'utf8')
  console.log('enums written to', OUT)
}

if (require.main === module) main()
