const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const SRC = path.resolve(ROOT, '..', 'Core.Driver', 'XmlSchema')
const OUT_DIR = path.resolve(ROOT, 'src', 'generated')
const OUT_JSON = path.join(OUT_DIR, 'schema.json')
const OUT_TS = path.join(OUT_DIR, 'schema.ts')

function walk(dir, acc = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      walk(full, acc)
    } else if (entry.isFile() && entry.name.endsWith('.cs')) {
      acc.push(full)
    }
  }
  return acc
}

function parseFile(filePath) {
  const text = fs.readFileSync(filePath, 'utf8')
  const fileName = path.basename(filePath, '.cs')
  const records = []
  const re = /public const string\s+(\w+)\s*=\s*"([^"]*)"/g
  let m
  while ((m = re.exec(text)) !== null) {
    const name = m[1]
    const value = m[2]
    const kind = name.startsWith('Ele')
      ? 'element'
      : name.startsWith('Atr')
        ? 'attribute'
        : name.startsWith('Val')
          ? 'default'
          : 'other'
    records.push({ name, value, kind })
  }
  return { fileName, records }
}

function buildSchema() {
  const files = walk(SRC)
  const schema = {}
  for (const file of files) {
    const { fileName, records } = parseFile(file)
    if (!schema[fileName]) {
      schema[fileName] = { elements: {}, attributes: {}, defaults: {} }
    }
    for (const r of records) {
      if (r.kind === 'element') schema[fileName].elements[r.name] = r.value
      else if (r.kind === 'attribute') schema[fileName].attributes[r.name] = r.value
      else if (r.kind === 'default') schema[fileName].defaults[r.name] = r.value
    }
  }
  return schema
}

function ensureOutDir() {
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true })
}

function writeOutputs(schema) {
  ensureOutDir()
  fs.writeFileSync(OUT_JSON, JSON.stringify(schema, null, 2), 'utf8')
  const ts = `// Auto-generated by scripts/extract-schema.js\n` +
    `// Do not edit manually.\n` +
    `export const QmfSchema = ${JSON.stringify(schema, null, 2)} as const;\n` +
    `export type QmfSchema = typeof QmfSchema;\n`
  fs.writeFileSync(OUT_TS, ts, 'utf8')
}

function main() {
  const schema = buildSchema()
  writeOutputs(schema)
  console.log(`QMF schema extracted to ${OUT_JSON}`)
}

if (require.main === module) {
  main()
}
